// <auto-generated />
using System;
using BarcodeGenerator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gapplus.Api.Migrations
{
    [DbContext(typeof(UsersContext))]
    [Migration("20240321132910_Rollback and Remigrate")]
    partial class RollbackandRemigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarcodeGenerator.Models.AGMQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AGMID")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeedback")
                        .HasColumnType("bit");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PercentageHolding")
                        .HasColumnType("float");

                    b.Property<string>("ReplyToEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyToMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyToName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShareholderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ShareholderNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("emailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("holding")
                        .HasColumnType("float");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shareholderquestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AGMQuestions");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.AppLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AGMID")
                        .HasColumnType("int");

                    b.Property<string>("AGMTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppLogs");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.BarcodeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AddedSplitAccount")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Clikapad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Consolidated")
                        .HasColumnType("bit");

                    b.Property<string>("ConsolidatedParent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsolidatedValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Holding")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotVerifiable")
                        .HasColumnType("bit");

                    b.Property<string>("OnlineEventUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentAccountNumber")
                        .HasColumnType("bigint");

                    b.Property<double>("PercentageHolding")
                        .HasColumnType("float");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Preregistered")
                        .HasColumnType("bit");

                    b.Property<bool>("Present")
                        .HasColumnType("bit");

                    b.Property<bool>("PresentByProxy")
                        .HasColumnType("bit");

                    b.Property<string>("Proxyupload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegCode")
                        .HasColumnType("int");

                    b.Property<long>("SN")
                        .HasColumnType("bigint");

                    b.Property<bool>("Selected")
                        .HasColumnType("bit");

                    b.Property<string>("SessionVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sessionid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ShareholderNum")
                        .HasColumnType("bigint");

                    b.Property<bool>("TakePoll")
                        .HasColumnType("bit");

                    b.Property<bool>("UserLoginHistory")
                        .HasColumnType("bit");

                    b.Property<string>("accesscode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("combined")
                        .HasColumnType("bit");

                    b.Property<string>("emailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("resolution")
                        .HasColumnType("bit");

                    b.Property<bool>("split")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BarcodeStore");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.Destination", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Messagesid")
                        .HasColumnType("int");

                    b.Property<int>("messageId")
                        .HasColumnType("int");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Messagesid");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.Facilitators", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AGMID")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilitatorCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnlineEventUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sessionid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UserLoginHistory")
                        .HasColumnType("bit");

                    b.Property<string>("accesscode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Facilitators");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.FacilitatorsArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AGMID")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilitatorCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnlineEventUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accesscode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FacilitatorsArchive");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.KeypadResults", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("AGMID")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keypad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keyvalue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeReceived")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Valuechecked")
                        .HasColumnType("bit");

                    b.Property<string>("voteReceived")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("KeypadResults");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.MailSettings", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("smtpHost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("smtpPort")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("mailsettings");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.Messages", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("callbackData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("flash")
                        .HasColumnType("bit");

                    b.Property<string>("from")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("intermediateReport")
                        .HasColumnType("bit");

                    b.Property<string>("notifyContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notifyUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sendAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transliteration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("validityPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.PresentArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AGMID")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clikapad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GivenClikapad")
                        .HasColumnType("bit");

                    b.Property<double>("Holding")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentNumber")
                        .HasColumnType("bigint");

                    b.Property<double>("PercentageHolding")
                        .HasColumnType("float");

                    b.Property<byte>("PermitPoll")
                        .HasColumnType("tinyint");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PresentTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ReturnedClikapad")
                        .HasColumnType("bit");

                    b.Property<long>("ShareholderNum")
                        .HasColumnType("bigint");

                    b.Property<bool>("TakePoll")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("Timestamp")
                        .HasColumnType("time");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("admitSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("newNumber")
                        .HasColumnType("bigint");

                    b.Property<bool>("preregistered")
                        .HasColumnType("bit");

                    b.Property<bool>("present")
                        .HasColumnType("bit");

                    b.Property<bool>("proxy")
                        .HasColumnType("bit");

                    b.Property<bool>("split")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PresentArchive");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.PresentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AGMID")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clikapad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GivenClikapad")
                        .HasColumnType("bit");

                    b.Property<double>("Holding")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentNumber")
                        .HasColumnType("bigint");

                    b.Property<double>("PercentageHolding")
                        .HasColumnType("float");

                    b.Property<byte>("PermitPoll")
                        .HasColumnType("tinyint");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PresentTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ReturnedClikapad")
                        .HasColumnType("bit");

                    b.Property<long>("ShareholderNum")
                        .HasColumnType("bigint");

                    b.Property<bool>("TakePoll")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("Timestamp")
                        .HasColumnType("time");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("admitSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("newNumber")
                        .HasColumnType("bigint");

                    b.Property<bool>("preregistered")
                        .HasColumnType("bit");

                    b.Property<bool>("present")
                        .HasColumnType("bit");

                    b.Property<bool>("proxy")
                        .HasColumnType("bit");

                    b.Property<bool>("split")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Present");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.ProxyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Holding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PercentageHolding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PresentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShareholderNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TakePoll")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("Timestamp")
                        .HasColumnType("time");

                    b.Property<string>("emailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("newNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("present")
                        .HasColumnType("bit");

                    b.Property<bool>("proxy")
                        .HasColumnType("bit");

                    b.Property<bool>("split")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Proxy");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.Proxylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ShareholderNum")
                        .HasColumnType("bigint");

                    b.Property<bool>("Validity")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ProxyList");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AGMID")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("questionStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("syncStatus")
                        .HasColumnType("bit");

                    b.Property<string>("voteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.QuestionArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AGMID")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("questionStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("syncStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("QuestionArchive");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AGMID")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clickapad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Holding")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentNumber")
                        .HasColumnType("bigint");

                    b.Property<double>("PercentageHolding")
                        .HasColumnType("float");

                    b.Property<bool>("Pregistered")
                        .HasColumnType("bit");

                    b.Property<bool>("Present")
                        .HasColumnType("bit");

                    b.Property<bool>("PresentByProxy")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<long>("ShareholderNum")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Timestamp")
                        .HasColumnType("time");

                    b.Property<bool?>("VoteAbstain")
                        .HasColumnType("bit");

                    b.Property<bool?>("VoteAgainst")
                        .HasColumnType("bit");

                    b.Property<string>("VoteChoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("VoteFor")
                        .HasColumnType("bit");

                    b.Property<string>("VoteStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("VoteVoid")
                        .HasColumnType("bit");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("splitValue")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.ResultArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AGMID")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clickapad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Holding")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentNumber")
                        .HasColumnType("bigint");

                    b.Property<double>("PercentageHolding")
                        .HasColumnType("float");

                    b.Property<bool>("Present")
                        .HasColumnType("bit");

                    b.Property<bool>("PresentByProxy")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<long>("ShareholderNum")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Timestamp")
                        .HasColumnType("time");

                    b.Property<bool?>("VoteAbstain")
                        .HasColumnType("bit");

                    b.Property<bool?>("VoteAgainst")
                        .HasColumnType("bit");

                    b.Property<bool?>("VoteFor")
                        .HasColumnType("bit");

                    b.Property<string>("VoteStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("VoteVoid")
                        .HasColumnType("bit");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("splitValue")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ResultArchive");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.SMSDeliveryLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("deliveryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("smsCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("QuestionId");

                    b.ToTable("SMSDeliveryLog");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.SMSResult", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("cleanText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("from")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("messageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receivedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("smsCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("QuestionId");

                    b.ToTable("SMSResult");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.SettingsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AGMID")
                        .HasColumnType("int");

                    b.Property<bool?>("AbstainBtnChoice")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdmittanceDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AgmDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AgmEnd")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AgmEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AgmStart")
                        .HasColumnType("bit");

                    b.Property<bool>("ArchiveStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountDownValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MessagingChoice")
                        .HasColumnType("bit");

                    b.Property<string>("OnlineUrllink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PreregisteredVotes")
                        .HasColumnType("bit");

                    b.Property<string>("PrintOutTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProxyVoteResult")
                        .HasColumnType("bit");

                    b.Property<int>("RegCode")
                        .HasColumnType("int");

                    b.Property<double>("ShareHolding")
                        .HasColumnType("float");

                    b.Property<bool>("StartAdmittance")
                        .HasColumnType("bit");

                    b.Property<bool>("StartVoting")
                        .HasColumnType("bit");

                    b.Property<bool>("StopAdmittance")
                        .HasColumnType("bit");

                    b.Property<bool>("StopVoting")
                        .HasColumnType("bit");

                    b.Property<string>("SyncChoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRecordCount")
                        .HasColumnType("int");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoteAbstaincolorBg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoteAgainstColorBg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoteForColorBg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoteVoidColorBg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("When")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("allChannels")
                        .HasColumnType("bit");

                    b.Property<string>("feebackCCEmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feebackEmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("mobileChannel")
                        .HasColumnType("bit");

                    b.Property<bool>("proxyChannel")
                        .HasColumnType("bit");

                    b.Property<bool>("smsChannel")
                        .HasColumnType("bit");

                    b.Property<bool>("ussdChannel")
                        .HasColumnType("bit");

                    b.Property<bool>("webChannel")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.SettingsModelArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AGMID")
                        .HasColumnType("int");

                    b.Property<bool?>("AbstainBtnChoice")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdmittanceDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AgmDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AgmEnd")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AgmEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AgmStart")
                        .HasColumnType("bit");

                    b.Property<bool>("ArchiveStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnlineUrllink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PreregisteredVotes")
                        .HasColumnType("bit");

                    b.Property<string>("PrintOutTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegCode")
                        .HasColumnType("int");

                    b.Property<double>("ShareHolding")
                        .HasColumnType("float");

                    b.Property<bool>("StartAdmittance")
                        .HasColumnType("bit");

                    b.Property<bool>("StopAdmittance")
                        .HasColumnType("bit");

                    b.Property<string>("SyncChoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRecordCount")
                        .HasColumnType("int");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoteAbstaincolorBg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoteAgainstColorBg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoteForColorBg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoteVoidColorBg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("When")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("allChannels")
                        .HasColumnType("bit");

                    b.Property<string>("feebackCCEmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feebackEmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("mobileChannel")
                        .HasColumnType("bit");

                    b.Property<bool>("proxyChannel")
                        .HasColumnType("bit");

                    b.Property<bool>("smsChannel")
                        .HasColumnType("bit");

                    b.Property<bool>("ussdChannel")
                        .HasColumnType("bit");

                    b.Property<bool>("webChannel")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SettingsArchive");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.ShareholderFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("When")
                        .HasColumnType("datetime2");

                    b.Property<string>("phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShareholderFeedback");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.UploadDatabase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Holding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PercentageHolding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ShareholderNum")
                        .HasColumnType("bigint");

                    b.Property<string>("emailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UploadDatabase");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("Gapplus.Domain.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompanyAddedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompanyUpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.Destination", b =>
                {
                    b.HasOne("BarcodeGenerator.Models.Messages", null)
                        .WithMany("destinations")
                        .HasForeignKey("Messagesid");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.Result", b =>
                {
                    b.HasOne("BarcodeGenerator.Models.Question", null)
                        .WithMany("result")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarcodeGenerator.Models.SMSDeliveryLog", b =>
                {
                    b.HasOne("BarcodeGenerator.Models.Question", null)
                        .WithMany("SMSdeliveryLog")
                        .HasForeignKey("QuestionId");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.SMSResult", b =>
                {
                    b.HasOne("BarcodeGenerator.Models.Question", null)
                        .WithMany("SMSResult")
                        .HasForeignKey("QuestionId");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.Messages", b =>
                {
                    b.Navigation("destinations");
                });

            modelBuilder.Entity("BarcodeGenerator.Models.Question", b =>
                {
                    b.Navigation("SMSResult");

                    b.Navigation("SMSdeliveryLog");

                    b.Navigation("result");
                });
#pragma warning restore 612, 618
        }
    }
}
